### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by AndrewRayCode** [raulghm/Font-Awesome-Stylus#21]
I'm new to stylus and don't know how to "import index.styl" in my .styl files. I've tried `@import "font-awesome-stylus"` but webpack croaks saying it can't find it.

**Comment by ajcarrillo** [comment]
The file is in the path "Font-Awesome-Stylus/stylus/", I prefer use the CDN server for font-awesome.
```
@import "Font-Awesome-Stylus/stylus/index.styl"
```

**Comment by DelvarWorld** [comment]
hmm.. does that mean I have to manually copy the source of this project into mine, or reference into the `node_modules` folder? Is there another way? For example, nib and jeet let you do this with webpack:


    var jeet = require('jeet');
    var nib = require('nib');

    config = { ...
        stylus: {
            use: [ nib(), jeet() ]
        },

**Comment by rlam3** [comment]
I'm having the same issue ... @DelvarWorld did you figure out how to get this working?

**Comment by rlam3** [comment]
I figured out I  could get it working like this, but don't know how to import the ones I only need instead of all of them

@import 'font-awesome-stylus'
$fa-font-path = 'font-awesome-stylus/stylus/index.styl'

@font-face
  font-family: 'FontAwesome';
  src: url('node_modules/font-awesome-stylus/fonts/fontawesome-webfont.eot');
  src: url('node_modules/font-awesome-stylus/fonts/fontawesome-webfont.eot') format('embedded-opentype'),
    url('node_modules/font-awesome-stylus/fonts/fontawesome-webfont.woff') format('woff'),
    url('node_modules/font-awesome-stylus/fonts/fontawesome-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;

**Comment by alexserver** [comment]
+1 for this request.
We need a clear example in the README.
How can we help ?

**Comment by raulghm** [comment]
Never is too late?

https://github.com/raulghm/Font-Awesome-Stylus/tree/master/recipes
